# Site settings
title: 'Code The Web'
description: 'Web development explained for normal people â€” Learn HTML, CSS and JavaScript in ways that you can actually understand!'
keyword: 'code the web, code the web blog, blog, web, web development, development, programming, internet, blog, website, html, css, javascript, learn, code, coding, learn to code, code web'
url: 'https://codetheweb.blog'
urlhost: 'codetheweb.blog' # site.url without protocol
baseurl: '/'

# Hide future posts
future: false

# Keep _redirects and _headers files in build
include: ['_redirects', '_headers']

# Navigation links
nav:
  home: '/'
  tags: '/tags'
  "newsletter &#127790; &#128640;": '/newsletter'

# Author
author: 'Ethan'
nickname: 'Ethan'
bio: "A self-taught programmer from Australia and creator of Code The Web. I program in HTML, CSS, JavaScript / NodeJS, Python and some random C++ release from the 90's."
avatar: 'assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: true

# Comments
disqus: true
disqus_url: 'https://codetheweb-blog.disqus.com/embed.js'

# Share
social-share: true
social-share-items: ['facebook', 'twitter', 'google']

# theme color
theme-color: 'pink'  # pink or default

# Post header background patterns (when the post has no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  # github: 'https://github.com/Booligoosh'
  website: 'https://ethan.link/'
  #twitter: 'https://twitter.com/Booligoosh' (icon doesn't work for some reason)
  # dribble: 'https://dribbble.com/Booligoosh'
  # medium: 'https://medium.com/@Booligoosh'

# Tags
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: '/page/:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: MyCustomProcessor
# These are now defined in markdown.rb:
# highlighter: rouge
# kramdown:
#   input: GFM

RSS: false

# Plugins
plugins: [jekyll-paginate, jekyll-sitemap]


# ME
defaults:
  -
    scope:
      path: "/demo/**"
    values:
      sitemap: false
  -
    scope:
      path: "/newsletters/**"
    values:
      sitemap: false
  -
    scope:
      path: "page"
    values:
      sitemap: false

sass:
  style: compressed
  
newsletter: /newsletter
share: '#share'
comments: '#disqus_thread'
contact: /contact
repo: https://github.com/CodeTheWebBlog/CodeTheWebBlog.github.io/
permalink: /:title/
sponsor: /sponsor
donate: https://buymeacoffee.com/CodeTheWeb
patreon: https://www.patreon.com/CodeTheWebBlog

email: 'hi@codetheweb.blog'

social:
  reddit: 'https://reddit.com/u/CodeTheWebBlog/'
  twitter: 'https://twitter.com/CodeTheWebBlog/'

wpm: 180

learn:
  html:
    tutorials:
      - /html-syntax/
      - /structure-of-an-html-document/
      - /basic-types-of-html-tags/
      - /links-images-about-file-paths/
      - /wrapping-and-grouping-elements/
      - /lists-and-navigation/
      - /html-icons/
    other:
      - /steps-to-creating-a-website/
      - /devchat/
      - /web-development-reference-sites/
      - /github-pages-free-hosting/
  css:
    tutorials:
      - /css-syntax/
      - /basic-css-properties/
      - /css-sizing-and-positioning/
      - /css-position-property/
      - /css-display-property/
      - /css-advanced-background-images/
      - /css-units/
      - /css-flexboxes/
      - /fullscreen-image-hero/
      - /style-a-navigation-bar-css/
      - /css-text-properties-and-google-fonts/
    other:
      - /steps-to-creating-a-website/
      - /devchat/
      - /web-development-reference-sites/
      - /github-pages-free-hosting/
  javascript:
    tutorials:
      - /hello-javascript/
      - /javascript-variables/
      - /if-statements-boolean-operators/
      - /javascript-math/
      - /for-and-while-loops-javascript/
      - /javascript-dialogs/
      - /javascript-functions/
      - /javascript-arrays/
      - /javascript-objects/
      - /javascript-dom/
      - /javascript-url-parsing/
      - /javascript-dates-and-times/
      - /javascript-timeouts-and-intervals/
      - /javascript-localstorage/
    other:
      - /devchat/
      - /web-development-reference-sites/
      - /github-pages-free-hosting/